print("     a     ")
print("    ABA    ")
print("   АВСВА   ")
print("  ABCDCBA  ")
print(" ABCDEDCBA ")
print("ABCDEFEDCBA")
print(" ABCDEDCBA ")
print("  ABCDCBA  ")
print("   АВСВА   ")
print("    ABA    ")
print("     A     ")